### ISSUE TITLE
imageImgixParams not being honoured to prevent format conversion

### ISSUE THREAD

**Issue by richard-underwood** [prismicio/prismic-gatsby#460]
### Versions

- gatsby-source-prismic: v4.2.0
- gatsby-plugin-prismic-previews: not installed
- node: v16.10.0

### Reproduction

Store a PNG image in Prismic, use imageImgixParams to prevent conversion to JPEG.

<details open>
<summary>Additional Details</summary>
<br>
Plugin configuraton:

```
    {
      resolve: 'gatsby-source-prismic',
      options: {
        repositoryName: process.env.PRISMIC_REPOSITORY_Name,
        accessToken: process.env.PRISMIC_ACCESS_TOKEN,
        customTypesApiToken: process.env.PRISMIC_CUSTOM_TYPES_API_TOKEN,
        typePrefix: process.env.PRISMIC_TYPE_PREFIX,
        lang: '*',
        imageImgixParams: {
          q: 100,
        },
      },
    },
```

GraphQL query (testing only):
```
query MyQuery {
  prismicModule {
    data {
      background_image {
        localFile {
          childImageSharp {
            original {
              src
            }
          }
        }
      }
    }
  }
}
```
</details>

### Steps to reproduce

1. Add an image to Prismic
2. Configure gatsby-source-prismic without auto=formatt
3. Check the file downloaded in the .cache folder

./caches/gatsby-source-prismic/xxxxx/xxx.png: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 1344x1058, frames 3

I have tried with auto="compress", auto="" and no auto in th eplugin configuration, in all cases the file is downloaded as a JPEG.

The .cache/caches/gatsby-source-prismic/diskstore-*.json file contains:

"key":"create-remote-file-node-headers-https://images.prismic.io/XXXX/xxx.png?auto=compress,format"

### What is expected?

The image should be downloaded as its original PNG to allow it to be converted efficiently with childImageSharp. 

### What is actually happening?

However, it's always being downloaded to the .cache folder as a JPEG, meaning when it is converted back to PNG it is larger than expected and contains JPEG compression artefacts.

**Comment by angeloashmore** [comment]
Hey @richard-underwood, sorry for the delay in response.

The Imgix options (`imageImgixParams` and `imagePlaceholderImgixParams`) are only for the Imgix image fields. These include `gatsbyImageData`, `fluid`, `fixed`, and `url`, but it does *not* include `localFile`.

After thinking about this more, I think the best approach is to keep it this way rather than have the Imgix params affect the locally downloaded file. The thinking here is that by using `localFile`, you are opting to let `gatsby-plugin-sharp` handle all image manipulation rather than Imgix.

What we can do, however, is remove the `auto` parameter for the downloaded `localFile` file. `auto=compress,format` is added by Prismic by default which will automatically compress and return the best format depending on the browser (WebP, AVIF, etc.). Since the file is downloaded in an Node.js context and the image will be compressed via `gatsby-plugin-sharp`, it makes sense to not have Imgix do this automatically.

I will make this change and let you know when it is available. If you have any thoughts on this, please feel free to share!

**Comment by richard-underwood** [comment]
Thanks for the reply, that makes complete sense and would solve my problem. Cheers.

**Comment by angeloashmore** [comment]
@richard-underwood Great, the change has been published in `v5.0.1`. Could you try it out and let me know if that fixes your issue?

**Comment by angeloashmore** [comment]
I just saw you are on V4. Here is a migration guide to go from V4 to V5: https://prismic.io/docs/technologies/gatsby-prismic-v4-to-v5

It should be fairly quick to upgrade. `v5.0.1` just also includes the ability to opt-in to all file downloads. If you don't want to list all of your files individually like it is shown in the migration guide, you can provide this instead:

```js
// Example gatsby-config.js file

module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-prismic',
      options: {
        // Alongside your other options...
        shouldDownloadFiles: true
      }
    }
  ]
}
```

**Comment by richard-underwood** [comment]
Thanks - I'll try an upgrade shortly.

**Comment by richard-underwood** [comment]
It's mostly working, but fails on one image - the height was wrong with the asset, but I think it's likely that the problem is because there are multiple dots in the filename. The image is served by Prismic as image/png.

```
        {
          "id": "602c25cd-xxxx-5adc-9212-bf4655bf7a07",
          "data": {
            "title": "xxxx",
            "images": [
              {
                "image": {
                  "localFile": null,
                  "dimensions": {
                    "height": 757,
                    "width": 1344
                  },
                  "url": "https://images.prismic.io/xxxx/e6b971f3-xxxx-41d6-9ec1-707e90a63826_CS1.1_Land.png?ixlib=gatsbyFP&auto=compress%2Cformat&fit=max&q=50"
                }
              }
            ]
          }
        }
```

**Comment by richard-underwood** [comment]
Hmm, I've found an instance which works that has two dots:

https://images.prismic.io/xxxx/c09bf29a-xxxx-4a66-bbf7-d5f64b620dc9_CS3.1_LAND.png

Is there a log I can look through anywhere?

**Comment by richard-underwood** [comment]
OK, I've restarted Gatsby develop, and it's now doing the same thing but on a different image in the same object, so it looks like it's random, possibly a timing error.

**Comment by angeloashmore** [comment]
@richard-underwood Thanks for the details. I will test on my side to see what is happening. Thanks for your patience - I'll post here once I know more.

**Comment by angeloashmore** [comment]
There isn't a built-in log to view what is happening right now, but you can add `console.log`s to the library files in node_modules.

I'll add a verbose log when files are downloaded to help debug these issues.

**Comment by angeloashmore** [comment]
@richard-underwood I just published `v5.0.3` with a fix that should solve your issue.

It turned out to be a garbage collection issue. More details are given here: https://github.com/prismicio/prismic-gatsby/pull/472

**Comment by richard-underwood** [comment]
Hi again, I think that's helped ... but it's still not working for me! At this point, it could be well be because I'm still on gatsby 3.14 (and gatby-plugin-sharp/gatsby-transformer-sharp 3.12) so if this shouldn't work, then please let me know and I'll start working on the bigger upgrade. However, if it should work with Gatsby 3 ... 

Currently I'm using the following fragment for localFIle:

```
    childImageSharp {
      webp: resize(toFormat: WEBP, height: 756) {
        src
        width
        height
        aspectRatio
      }
      png: resize(toFormat: PNG, height: 756) {
        src
        width
        height
        aspectRatio
      }
    }
```

In every case, I now get a src back, e.g. "/static/8431468ccc297f8a699938ccc9d667a8/2687a/5930c39e-xxxx-4e43-9a7d-2ef36489dc3f_E3-C1-CS_LAND.webp" however, in every case the first directory (public/static/8431468ccc297f8a699938ccc9d667a8 in this case) is empty and so the URI generates a 404 page (gatsby develop, I've not tried build).

Thanks!

**Comment by richard-underwood** [comment]
I've run the outstanding updates I have (to Gatsby v4) and it's all working now, so I think it's best to leave it be.

Thanks for all your help, all working as expected now.

**Comment by richard-underwood** [comment]
@angeloashmore Apologies for replying to a closed issue - let me know if you'd like a new issue opened. Everything is working for me and the build server in AWS, but our Indian development team aren't able to work. 

```
$ gatsby develop --verbose
verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "develop"
verbose loading local command from: /Users/xxxx/Work/xxxx/gatsby-website/node_modules/gatsby/dist/commands/develop.js
verbose running command: develop
 
verbose Transition to "initializing"
success open and validate gatsby-configs, load plugins - 4.022s
success onPreInit - 0.004s
success initialize cache - 0.260s
success copy gatsby files - 0.198s
verbose Attaching functions to development server
success Compiling Gatsby Functions - 0.638s
success onPreBootstrap - 0.668s
verbose Creating 3 worker
verbose Transition to "initializingData"
success createSchemaCustomization - 2.966s
verbose Transition to "initializingData" > "sourcingNodes"
verbose gatsby-source-prismic(xxxx) - Attempting to download and cache file:
https://images.prismic.io/xxxx/21fb4af7-xxxx-42f1-89e9-8cc21b60e2dd_Image.png
verbose gatsby-source-prismic(xxxx) - Attempting to download and cache file:
https://images.prismic.io/xxxx/68139eec-xxxx-430b-9622-c14564a45e1e_Vector.png
[... 349 similar entries ...]
verbose gatsby-source-prismic(xxxx) - Attempting to download and cache file:
https://images.prismic.io/xxxx/12e36494-xxxx-4091-9b0e-37ee097b3478_E3_C1_1.2.png
 
ERROR
 
Failed to download https://images.prismic.io/xxxx/21fb4af7-xxxx-42f1-89e9-8cc21b60e2dd_Image.png after 3 attempts
 
not finished source and transform nodes - 95.428s
```

I've had a look and found a number of previous issues with the same error, but no real solution (other than disabling image downloads and using Imgix instead).

This may be a Gatsby bug, rather than a Prismic one, but do you have any idea why it could be an issue? It was working for them before the upgrade.

Thanks.

**Comment by angeloashmore** [comment]
@richard-underwood No problem about replying to this thread. If there's a larger issue that we can't solve immediately, then yes, we can move this to a new issue.

This could be happening due network timeouts or unstable connections, potentially related to the geographical differences. File downloading is handled by `gatsby-source-filesystem` so there isn't much I can do in the Prismic plugin. You could have them try different values for these environment variables:

- `GATSBY_STALL_RETRY_LIMIT`, default: `3`
- `GATSBY_STALL_TIMEOUT`, default: `30000`
- `GATSBY_CONNECTION_TIMEOUT`, default: `30000`

More details here: https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/#troubleshooting
